name: starter_architecture_flutter_firebase
description: A new Flutter project.

publish_to: 'none'
version: 2.1.0

environment:
  sdk: ">=3.1.0 <4.0.0"

dependencies:
  cloud_firestore: ^5.0.2
  cupertino_icons: ^1.0.8
  equatable: ^2.0.5
  firebase_auth: ^5.0.0
  firebase_auth_web: ^5.12.3
  firebase_core: ^3.1.1
  firebase_ui_auth: ^1.15.0
  firebase_ui_firestore: ^1.6.4
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  flutter_svg: ^2.0.10
  go_router: 14.2.0
  intl: ^0.19.0
  rxdart: ^0.27.7
  shared_preferences: ^2.2.3
  speech_to_text: ^6.6.2
  # flutter_tts: ^4.0.2
  # the annotation package containing @riverpod
  riverpod_annotation: 2.3.5
  firebase_vertexai: ^0.2.2+1
  flutter_markdown: ^0.7.3
  google_fonts: ^6.2.1
  icons_launcher: ^2.1.3
  animated_text_kit: ^4.2.2
  flutter_dotenv: ^5.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.3
  random_string: ^2.3.1
  flutter_lints: ^4.0.0
  # a tool for running code generators
  build_runner: ^2.4.10
  # the code generator
  riverpod_generator: 2.4.0
  # riverpod_lint makes it easier to work with Riverpod
  riverpod_lint: 2.3.10
  # import custom_lint too as riverpod_lint depends on it
  custom_lint: 0.6.4


flutter:
  uses-material-design: false
  assets:
    - assets/fonts/
    - assets/time-tracking.svg
